SOURCE = hello.cpp
BIN = hello.exe
OBJ = hell.o
CXX = g++
CXXFLAGS = -std=c++17

$(BIN): $(OBJ)
	$(CXX) $(OBJ) -o $(BIN) $(CXXFLAGS)
run: $(BIN)
	$(BIN)
$(OBJ): $(SOURCE)
	$(CXX)	-c $(SOURCE) -o $(OBJ) $(CXXFLAGS) 	  
